[package]
name = "windows_app_bindings"
version = "0.2.0"
authors = ["Microsoft"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Implementation for windows-app crate"

[dependencies]
windows = "0.12.0"

[build-dependencies]
windows = "0.12.0"
